version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-node-app:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag my-node-app:$CODEBUILD_RESOLVED_SOURCE_VERSION 264581932457.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Pushing the Docker image to ECR...
      - docker push 264581932457.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:$CODEBUILD_RESOLVED_SOURCE_VERSION

post_build:
  commands:
    - echo Build completed on `date`
    - echo Triggering Blue/Green deployment...
    - aws deploy create-deployment \
        --application-name my-node-app-application \
        --deployment-group-name my-node-app-deployment-group \
        --revision revisionType=AppSpecContent,s3Location={bucket=codedeploy-bucket,key=appspec.yml,bundleType=YAML} \
        --deployment-config-name CodeDeployDefault.ECSAllAtOnce
